before:
  hooks:
    - go mod tidy
    - go fmt ./...
    - go test ./...

builds:
  - id: tcols
    main: ./cmd/tcols
    binary: tcols
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .CommitDate }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - linux_riscv64
      - windows_amd64
      - windows_arm64
      - windows_arm
      - darwin_amd64
      - darwin_arm64

universal_binaries:
  - id: tcols
    replace: true
    name_template: tcols

archives:
- id: tcols
  format: tar.gz
  builds:
    - tcols
  files:
  - none*
  name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers:
  - id: tools
    goos: linux
    goarch: amd64
    ids:
      - tcols
    image_templates:
      - "ghcr.io/mdm-code/tcols:latest"
      - "ghcr.io/mdm-code/tcols:{{ .Tag }}"
      - "ghcr.io/mdm-code/tcols:v{{ .Major }}"
    skip_push: false

checksum:
  name_template: 'sha256sums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

release:
  github:
    owner: mdm-code
    name: termcols
  draft: true
  prerelease: auto
  mode: replace

changelog:
  use: github-native

announce:
  skip: true
